# Generated by Django 5.2 on 2025-05-08 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pasien', models.CharField(max_length=100)),
                ('patient_id', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='MCURecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('urine_color', models.PositiveSmallIntegerField(choices=[(0, 'Dehidrasi'), (1, 'Cukup'), (2, 'Baik')])),
                ('alcohol_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('body_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcu_records', to='medisapp.patient')),
            ],
        ),
    ]
