# Generated by Django 5.2 on 2025-05-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medisapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='alamat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default=1, help_text='nomor telpon indonesia', max_length=15),
            preserve_default=False,
        ),
    ]
