# Generated by Django 5.2 on 2025-05-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medisapp', '0003_alter_patient_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Laki-laki'), (1, 'Perempuan')]),
        ),
    ]
